#! /bin/sh

# simple-templater - Copyright 2014 Alan De Smet
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

read_field() {
	filename=$1
	field=$2
	grep -i "^%$field% " $filename | sed "s/^%$field% //"
}

template=$1
filename=$2
destination=$3

if [ "$destination" = "" ]; then
	cat <<END
Usage: $0 <template-file> <input-file> <output-file>
END
	exit 1
fi

TITLE=`tempfile`
read_field "$filename" TITLE > $TITLE

EXTRAHEADER=`tempfile`
read_field "$filename" EXTRAHEADER > $EXTRAHEADER

BODY=`tempfile`
grep -v '^%[^%]*% ' "$filename" > $BODY

sed \
	-e "/^%TITLE% *$/ {" -e "r $TITLE" -e 'd' -e '}'  \
	-e "/^%EXTRAHEADER% *$/ {" -e "r $EXTRAHEADER" -e 'd' -e '}'  \
	-e "/^%BODY% *$/ {" -e "r $BODY" -e 'd' -e '}'  \
	$template > $destination

if [ "$filename" = "thanks_and_acknowledgements.htm" ]; then
	sed -i 's/.*data-cc="true".*/<p>The text of this page is from the Mythender Roleplaying Game, written and published by Ryan Macklin, and used with permission.<\/p>/' $destination
fi

rm $TITLE $EXTRAHEADER $BODY
